version: '2'
networks:
  jenkins:
services:
  jenkins:
    container_name: jenkins
    image: jimbrighter/jenkins:latest
    ports:
      - "80:8080"
      - "50000:50000"
    mem_limit: 3840m
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/jbrighter/jenkins_home:/var/jenkins_home
      - /home/jbrighter/.ssh:/var/jenkins_home/.ssh
    networks:
      jenkins:
        aliases:
          - jenkins
    env_file: secrets.env
