version: '2'
networks:
  jenkins:
services:
  jenkins:
    container_name: jenkins
    image: jimbrighter/jenkins:latest
    mem_limit: 3840m
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/jbrighter/jenkins_home:/var/jenkins_home
      - /home/jbrighter/.ssh:/var/jenkins_home/.ssh
    networks:
      jenkins:
        aliases:
          - jenkins
    env_file: secrets.env
  nginx:
    container_name: nginx
    image: jimbrighter/jenkins-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    mem_limit: 25m
    restart: always
    networks:
      jenkins:
        aliases:
          - nginx
    volumes:
      - /home/jbrighter/keystores:/certs
